#!/bin/bash

set -e

if [ ! -e /opt/autoscaler/venv ]; then
    mkdir -p /opt/autoscaler
    python3 -m venv /opt/autoscaler/venv
    . /opt/autoscaler/venv/bin/activate
    python3 -m pip install openstacksdk python-dateutil
else
    . /opt/autoscaler/venv/bin/activate
fi

cd /srv/osg-jetstream/salt/autoscaler
python3 autoscaler.py

